[tool.pytest.ini_options]
log_cli = true
log_cli_level = "CRITICAL"
log_cli_format = "%(message)s"

log_file = "pytest.log"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_file_date_format = "%Y-%m-%d %H:%M:%S"

markers = [
    "negative: marker for negative tests",
    "params: marker for parametrized tests",
    "adv_inheritance: marker for inheritance advantages tests",
    "basket: marker for basket tests",
    "login_guest: marker for login guest tests",
    "user_tests_with_registartion: marker for user tests of product page",
    "need_review: marker for review tests"
]